### ISSUE TITLE
Add support for doc-view

### ISSUE THREAD

**Issue by jumper047** [dalanicolai/pdf-continuous-scroll-mode.el#11]
Sometimes I using Emacs to read some doc/odt documents, and these moments I missing your package. Is it possible to support an doc-view too?

**Comment by dalanicolai** [comment]
Yes that's possible and I already ported it to doc-view. However, I continued to experiment to integrate the djvu package functionality within doc-view. So I changed the files while I forgot to save a snapshot from the working doc-view port. Reverting those files is not too much work, but I'm afraid I have no time to do it. The files can be found [here](https://github.com/dalanicolai/dala-emacs-lisp#doc-view-continuous-scrollel).

On the other hand, I have just created a Spacemacs layer for the [Emacs Application Framework](https://github.com/manateelazycat/emacs-application-framework). I suggest you to check out EAF (the webbrowser is especially nice). If you use Spacemacs, then you can install the layer [as soon as it gets merged](https://github.com/syl20bnr/spacemacs/pull/14291). Otherwise you can install EAF directly. EAF includes the `eaf-open-office` command for (continuous-)viewing odt/doc(x) files.

**Comment by jumper047** [comment]
I am aware of it but unfortunately it only works on Linux. Sadly some times I need Windows too. Thank you for link - maybe I'll have spare time earlier then you:)

**Comment by dalanicolai** [comment]
Okay so I made a very quick attempt [here](doc-view-continuous-scroll-mode) to revert it to a working state again. It is not debugged at all, but it works somewhat... at least worth to try it
Just evaluate the code and activate `doc-view-continuous-scroll-mode` from your doc-view buffer.

**Comment by jumper047** [comment]
Fixed another one string to delete -  https://github.com/dalanicolai/dala-emacs-lisp/pull/1
Now all works perfectly. Thank you again!

**Comment by dalanicolai** [comment]
Great! Thanks for the fix! Has been merged. Enjoy!
