### ISSUE TITLE
Backward scroll of beamer pdf slides creates stack of buffers

### ISSUE THREAD

**Issue by averter** [dalanicolai/pdf-continuous-scroll-mode.el#21]
This  is a great package which works perfectly to visualize portrait oriented pdf files. However, when I try to use it on beamer landscape pdf slides, as soon as I start backscrolling (using the upward arrow key) this mode keeps stacking buffers on top of each other. Like so
![Untitled](https://user-images.githubusercontent.com/16647523/160471097-ce997d4c-bafd-4bca-948a-7cb6b477e96d.png)
So my question is if there a workaround which does not interfere with the display of the portrait oriented pdf files? If needed this [template](https://www.overleaf.com/latex/templates/usach-theme-es/pfzycyrgphds) can be used for testing purposes. Thank you in advance.

**Comment by dalanicolai** [comment]
Thank you for your report. First, I am wondering which version you are using, as I think the latest version should never create new buffers. So I guess you are using some older version, I think in that version there is no easy fix or workaround for this.

However also the current/most recent version has quite some bugs, and does also not handle landscape pdfs correctly. I have been working on a little cleaner version in the [continuous-scroll-version-3 branch of my pdf-tools fork](https://github.com/dalanicolai/pdf-tools), which should work a little better in general, but also that version unfortunately does not work (yet) with landscape slides.

Unfortunately, the Emacs display mechanism and the pdf-tools package are both quite complex and therefore, fixing any of the bugs takes considerable time for investigation and for implementing the fix. Unfortunately, I have no resources (time nor money) to work much more on this package so that I am unable to investigate this bug. On the other hand, I expect this would be one of the relatively simple to fix bugs and I could offer all my assistance. (Maybe when I have some more time at some point, I could create a kickstarter for this and try to find some sponsors...)

**Comment by averter** [comment]
Thanks for your work and quick reply. 
Indeed, I have recently updated to the latest version and am experiencing the two issues reported https://github.com/dalanicolai/pdf-continuous-scroll-mode.el/issues/15 and https://github.com/dalanicolai/pdf-continuous-scroll-mode.el/issues/16. Probably this is due to the fact that I am using Gnu Emacs 27.2; quite different from spacemacs? I might revert back temporarily to the two buffers version until these issues are fixed, but in any case I will be following new developments closely. Thanks and closing for now.
