### ISSUE TITLE
error

### ISSUE THREAD

**Issue by brioglade** [dalanicolai/pdf-continuous-scroll-mode.el#4]
Errors:
    - 
      An error occurred while installing pdf-continuous-scroll-mode (error: (error Package ‘emacs-27.1’ is unavailable))
    -

**Comment by danilevy1212** [comment]
Perhaps you don't have the correct emacs version? It's hard to tell without any more context.

Confirm with  `M-x emacs-version`, it needs to be 27.1 or higher.

**Comment by brioglade** [comment]
It still didn't work when I updated to be 27.1 and no error occur in the installation precess.
I found that there was no command M-x pdf-continuous-scroll-mode in the list.

**Comment by danilevy1212** [comment]
How are you installing it? If you download the file and source it, does it work? If I had to guess, the problem may be that the package is not loaded with your installation method. Is the package part of your `load-path`?

Unfortunately, if you are using spacemacs I cannot help you much more than this since I am not a spacemacs user.

**Comment by dalanicolai** [comment]
@danilevy1212 Thanks! Did not see this earlier. @brioglade I hope it works now...
