### ISSUE TITLE
scroll-forward abruptly creates a bisecting buffer

### ISSUE THREAD

**Issue by bytewife** [dalanicolai/pdf-continuous-scroll-mode.el#8]
Hello! This package is fantastic, but I cannot seem to fix this issue: When I use pdf-continuous-scroll-forward to a get to a new page, the new page's buffer immediately takes up half the screen. [Demo](https://i.imgur.com/KSlZjHA.mp4)

scroll-backward works well though.

**Comment by dalanicolai** [comment]
Hi thanks for reporting! Due to this issue, I noticed that the code in the package did not conform with that in the elisp manual. Therefore, I have reformatted the display function. So, although it should not make a difference, you could first try to update the package.

As updating probably will not solve it, here follows some info and a suggestion:
The package uses the following display function to create the buffer below the 'pdf-view buffer'
```
                     (display-buffer
                      (current-buffer)
                      '((display-buffer-below-selected)
                        (inhibit-same-window . t)
                        (window-height . 1)))
```
The last line of the function means that the display function should try to create a buffer with line height equal to 1 (or maybe pixel height, but it is irrelevant here).
So maybe try `M-:` `(setq window-safe-min-height 1)`. Let me know if that does not solve it (although I can not think of any other solution right now), or when it solves then you could close this issue.

**Comment by bytewife** [comment]
I updated the package, as well as set the window-safe-min-height to 1, but the issue remains. Please let me know if you come up with anything, or need to see any of my build's info. I'll be doing some testing as well.

**Comment by dalanicolai** [comment]
Unfortunately, I don't have any other suggestion right now. But of course, you could start by checking what happpens when you just [evaluate](https://www.gnu.org/software/emacs/manual/html_node/eintr/How-to-Evaluate.html#How-to-Evaluate) the display function I have sent in [the comment above](https://github.com/dalanicolai/pdf-continuous-scroll-mode.el/issues/8#issuecomment-715917167). There should open another window of 1 line height below your curent buffer.

**Comment by teu5us** [comment]
I ended up overriding `pdf-continuous-scroll-forward-line` to use `window-min-height` (which is 4 by default I think) instead of 1. It is a bit choppy, but still much better

**Comment by dalanicolai** [comment]
Thanks for reporting possible solutions! Did you set it by setting the `pdf-cs-custom-min-height` variable, which is meant for that?

**Comment by teu5us** [comment]
I will try the variable later

**Comment by teu5us** [comment]
The variable has no effect for me. Also, it's so string seems wrong

**Comment by dalanicolai** [comment]
Ah okay. Looking closer into it, it seems that window-min-height is not used in `pdf-continuous-scroll-forward-line`, but only in the `backward` version.

**Comment by dalanicolai** [comment]
Closing the issue for archiving this repo. A better implementation is available at https://github.com/dalanicolai/image-roll.el
